In [ ]:
import urllib.request
import urllib.parse
import json
import pandas as pd
import pprint
import time
from tqdm.auto import tqdm
import numpy as np
import re

# 2005年から2018年までの出荷ランキングなど

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
    p = json.load(f)

# 2019年と2020年は統計表の構造が違うので2005年から2018年でまずは作る
statsDataId_list_from2005_to2018 = ["0003001090", "0003001097","0003001098","0003001102","0003001105","0003001107","0003001113","0003001114","0003001121","0003001123","0003001125", #秋冬はくさい
"0003001126","0003001129","0003001130","0003001132","0003001330","0003001115","0003001133","0003001138","0003001144","0003001148","0003001146","0003001145", #秋冬ねぎ
"0003001137","0003001136","0003001104","0003001106","0003001075","0003001076","0003001077","0003001080","0003001082","0003001089", #2005年
"0003006921","0003006922","0003006923","0003006926","0003006927","0003006928","0003006932","0003006933","0003006940","0003006941","0003006942", #秋冬はくさい
"0003006943","0003006945","0003006946","0003006947","0003006949","0003006953","0003006959","0003006961","0003006963","0003006966","0003006967","0003006968", #秋冬ねぎ
"0003006973","0003006974","0003006982","0003006983","0003006984","0003006985","0003006986","0003006989","0003006991","0003006996", #2006年
"0003011927","0003011928","0003011929","0003011932","0003011933","0003011934","0003011938","0003011939","0003011946","0003011947","0003011948", #秋冬はくさい
"0003011949","0003011951","0003011952","0003011953","0003011955","0003011959","0003011965","0003011967","0003011969","0003011972","0003011973","0003011974", #秋冬ねぎ
"0003011979","0003012048","0003012056","0003012057","0003012058","0003012059","0003012060","0003012063","0003012065","0003012070", #2007年
"0003017642","0003017643","0003017644","0003017647","0003017648","0003018502","0003018506","0003018507","0003018514","0003018515","0003018516", #秋冬はくさい
"0003018517","0003018519","0003018520","0003018521","0003018523","0003018527","0003018533","0003018535","0003018537","0003018540","0003018541","0003018542", #秋冬ねぎ
"0003018547","0003018548","0003018556","0003018557","0003018558","0003018559","0003018560","0003018563","0003018565","0003018570", #2008年
"0003047434","0003047435","0003048491","0003048494","0003048495","0003048496","0003048500","0003048501","0003048508","0003048509","0003048510", #秋冬はくさい
"0003048511","0003048513","0003048514","0003048515","0003048517","0003048521","0003048527","0003048529","0003048531","0003048534","0003048535","0003048536", #秋冬ねぎ
"0003048541","0003048542","0003048550","0003048551","0003048552","0003048553","0003048554","0003048557","0003048559","0003048564", #2009年
"0003067554","0003067555","0003067556","0003067559","0003067560","0003067561","0003067565","0003067566","0003067573","0003067574","0003067575", #秋冬はくさい
"0003067576","0003067578","0003067579","0003067580","0003067582","0003067587","0003067593","0003067595","0003067597","0003067600","0003067601","0003067602", #秋冬ねぎ
"0003067607","0003067608","0003067616","0003067617","0003067618","0003067619","0003067620","0003067623","0003067625","0003067630", #2010年
"0003078966","0003078997","0003078997","0003078998","0003078935","0003078979","0003078980","0003078969","0003078982","0003078971","0003079002", #秋冬はくさい
"0003079019","0003078972","0003079003","0003079020","0003078973","0003079005","0003078987","0003079007","0003078988","0003079025","0003078989","0003079038", #秋冬ねぎ
"0003079010","0003079027","0003079029","0003078993","0003079042","0003079013","0003079030","0003079014","0003078995","0003079045", #2011年
"0003092981","0003092936","0003092948","0003092937","0003092949","0003092970","0003092971","0003092984","0003092973","0003092986","0003093001", #秋冬はくさい
"0003092953","0003092987","0003093002","0003092954","0003092988","0003093004","0003092978","0003093006","0003092979","0003092959","0003092980","0003092993", #秋冬ねぎ
"0003093009","0003093041","0003093043","0003093024","0003092997","0003093012","0003093044","0003093013","0003093026","0003093000", #2012年
"0003103576","0003103538","0003103615","0003103539","0003103616","0003103595","0003103596","0003103579","0003103598","0003103581","0003103543", #秋冬はくさい
"0003103620","0003103582","0003103544","0003103621","0003103583","0003103626","0003103603","0003103628","0003103604","0003103666","0003103685","0003103648", #秋冬ねぎ
"0003103631","0003103668","0003103670","0003103689","0003103652","0003103634","0003103671","0003103635","0003103691","0003103637", #2013年
"0003127270","0003127355","0003127338","0003127356","0003127339","0003127318","0003127319","0003127373","0003127321","0003127375","0003127360", #秋冬はくさい
"0003127343","0003127376","0003127361","0003127344","0003127377","0003127363","0003127326","0003127365","0003127327","0003127349","0003127328","0003127382", #秋冬ねぎ
"0003127368","0003127351","0003127393","0003127332","0003127386","0003127371","0003127394","0003127372","0003127414","0003127434", #2014年
"0003171581","0003171503","0003171601","0003171504","0003171602","0003171622","0003171623","0003171584","0003171625","0003171586","0003171508", #秋冬はくさい
"0003171606","0003171587","0003171509","0003171607","0003171588","0003171511","0003171630","0003171513","0003171631","0003171612","0003171632","0003171593", #秋冬ねぎ
"0003171516","0003171614","0003171616","0003171636","0003171597","0003171519","0003171617","0003171640","0003171638","0003171642", #2015年
"0003216474","0003216475","0003216476","0003216479","0003216480","0003216481","0003216485","0003216486","0003216493","0003216494","0003216495", #秋冬はくさい
"0003216496","0003216498","0003216499","0003216500","0003216502","0003216507","0003216513","0003216515","0003216517","0003216520","0003216521","0003216522", #秋冬ねぎ
"0003216527","0003216528","0003216536","0003216537","0003216538","0003216539","0003216540","0003216543","0003216545","0003216551",#2016年
"0003289849","0003289850","0003289851","0003289854","0003289855","0003289856","0003289860","0003289861","0003289868","0003289869","0003289870", #秋冬はくさい
"0003289871","0003289873","0003289874","0003289875","0003289877","0003289882","0003289888","0003289890","0003289892","0003289895","0003289896","0003289897", #秋冬ねぎ
"0003289902","0003289903","0003289911","0003289912","0003289913","0003289914","0003289915","0003289918","0003289920","0003289926", #2017年
"0001799304","0001799305","0001799306","0001799309","0001799310","0001799311","0001799315","0001799316","0001799322","0001799323","0001799324", #秋冬はくさい
"0001799325","0001799327","0001799328","0001799329","0001799331","0001799336","0001799342","0001799344","0001799346","0001799349","0001799350","0001799351", #秋冬ねぎ
"0001799356","0001799357","0001799365","0001799366","0001799367","0001799368","0001799369","0001799372","0001799374","0001799380", #2018年
]

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_from2005_to2018 = pd.DataFrame()
df_list = []

# 各statsDataIdで
for i, statsDataId in tqdm(enumerate(statsDataId_list_from2005_to2018)):
  # url取得
  p["statsDataId"] = statsDataId
  print(p["statsDataId"])
  url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

  with urllib.request.urlopen(url) as response:
    data = response.read()
  d = json.loads(data.decode())

  # 統計表をデータフレーム化
  table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
  df_ = pd.io.json.json_normalize(table_info_list, sep='_')

  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった

  try:
    df_ = df_.pivot(index="@area", columns="@cat01", values="$").reset_index()
  except KeyError:
    df_ = df_.pivot(index="@area", columns="@cat02", values="$").reset_index()
  
  # 統計表での欠損の意味に近い文字列は欠損値扱い("やや不良", "やや良"は作物の生産量の事だと思うが見たことがない。もしあるなら、ほかの変換方法は考えるべきかと)
  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "やや不良", "やや良"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)

  # @area(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][1]["CLASS"]
  df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})

  # 統一したカラム名で更新
  df_.columns = ["area", "作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比"]

  # 数値データが str型になっているので、float型に変換
  float_columns = ["作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比",]
  df_[float_columns] = df_[float_columns].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']

  # 野菜の名前(name)を追加('TABLE_SUB_CATEGORY3'は「うち、ミニトマト」、CATEGORY2は「冬春トマト」、CATEGORY1は「トマト」のように、カテゴリーの数値が小さいほど野菜としての定義が広くなる)
  try:
    try:
      df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY3']
    except KeyError:
      df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY2']
  except KeyError:
    df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY1']

  # 途中の年から、CATEGORY2が「冬春」のように省略されるようになったので、CATEGORY1と結合することで統一性を保つ
  # 省略後のCATEGORY2は基本2文字だが、「ばれいしょ」のみ3文字であった(また、３文字は「春ネギ」などがあり文字指定するとそっちも更新されてしまう)ため、
  # 「ばれいしょ」のみ単独で更新、ほかの季節のみnameは2文字指定で更新(２文字以下の野菜はない(ねぎは季節が必ず付くから大丈夫))
  if df_["name"][0]=="春植え" or df_["name"][0]=="秋植え":
    df_["name"] = df_["name"] + "ばれいしょ"
  if len(df_["name"][0]) <= 2:
    df_["name"] = df_["name"] + d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY1']

  # トマトからミニトマトと加工用トマト分を引く
  amount_columns = ["作付面積", "収穫量", "出荷量"]
  if re.match(r'うち、*', df_["name"][0]) != None:
    df_["name"] = df_["name"] + d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY2']
    if re.match(r'うち、*', df_list[i-1]["name"][0]) != None:
      for amount_column in amount_columns:
        df_list[i-2][amount_column] = df_list[i-2][amount_column] - df_[amount_column]
      df_list[i-2]["出荷量ランキング"] = df_list[i-2]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-2]["収穫量 - 出荷量"] = df_list[i-2]["収穫量"] - df_list[i-2]["出荷量"]
    else:
      for amount_column in amount_columns:
        df_list[i-1][amount_column] = df_list[i-1][amount_column] - df_[amount_column]
      df_list[i-1]["出荷量ランキング"] = df_list[i-1]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-1]["収穫量 - 出荷量"] = df_list[i-1]["収穫量"] - df_list[i-1]["出荷量"]

  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
  # 収穫量 - 出荷量 を作成
  df_["収穫量 - 出荷量"] = df_["収穫量"] - df_["出荷量"]

  def season_move_2005_2018_str(s_):
    season = re.search(r"[春夏秋冬]{1,2}", s_)
    yasai = re.search(r"ミニトマト|加工用トマト", s_)
    if season is not None and yasai is not None:
      return season.group() + yasai.group()
    else:
      return s_
  df_["name"] = df_["name"].map(season_move_2005_2018_str)

  # df_をリストに追加
  df_list.append(df_)

  # sleep入れる
  time.sleep(1)

# df_listからdfを作成
df_from2005_to2018 = pd.concat(df_list, axis=0, ignore_index=True)

0it [00:00, ?it/s]

0003001090

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:66: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

0003001097
0003001098
0003001102
0003001105
0003001107
0003001113
0003001114
0003001121
0003001123
0003001125
0003001126
0003001129
0003001130
0003001132
0003001330
0003001115
0003001133
0003001138
0003001144
0003001148
0003001146
0003001145
0003001137
0003001136
0003001104
0003001106
0003001075
0003001076
0003001077
0003001080
0003001082
0003001089
0003006921
0003006922
0003006923
0003006926
0003006927
0003006928
0003006932
0003006933
0003006940
0003006941
0003006942
0003006943
0003006945
0003006946
0003006947
0003006949
0003006953
0003006959
0003006961
0003006963
0003006966
0003006967
0003006968
0003006973
0003006974
0003006982
0003006983
0003006984
0003006985
0003006986
0003006989
0003006991
0003006996
0003011927
0003011928
0003011929
0003011932
0003011933
0003011934
0003011938
0003011939
0003011946
0003011947
0003011948
0003011949
0003011951
0003011952
0003011953
0003011955
0003011959
0003011965
0003011967
0003011969
0003011972
0003011973
0003011974
0003011979
0003012048
0003012056
0003012057
0003012058
0003012059
0003012060
0003012063
0003012065
0003012070
0003017642
0003017643
0003017644
0003017647
0003017648
0003018502
0003018506
0003018507
0003018514
0003018515
0003018516
0003018517
0003018519
0003018520
0003018521
0003018523
0003018527
0003018533
0003018535
0003018537
0003018540
0003018541
0003018542
0003018547
0003018548
0003018556
0003018557
0003018558
0003018559
0003018560
0003018563
0003018565
0003018570
0003047434
0003047435
0003048491
0003048494
0003048495
0003048496
0003048500
0003048501
0003048508
0003048509
0003048510
0003048511
0003048513
0003048514
0003048515
0003048517
0003048521
0003048527
0003048529
0003048531
0003048534
0003048535
0003048536
0003048541
0003048542
0003048550
0003048551
0003048552
0003048553
0003048554
0003048557
0003048559
0003048564
0003067554
0003067555
0003067556
0003067559
0003067560
0003067561
0003067565
0003067566
0003067573
0003067574
0003067575
0003067576
0003067578
0003067579
0003067580
0003067582
0003067587
0003067593
0003067595
0003067597
0003067600
0003067601
0003067602
0003067607
0003067608
0003067616
0003067617
0003067618
0003067619
0003067620
0003067623
0003067625
0003067630
0003078966
0003078997
0003078997
0003078998
0003078935
0003078979
0003078980
0003078969
0003078982
0003078971
0003079002
0003079019
0003078972
0003079003
0003079020
0003078973
0003079005
0003078987
0003079007
0003078988
0003079025
0003078989
0003079038
0003079010
0003079027
0003079029
0003078993
0003079042
0003079013
0003079030
0003079014
0003078995
0003079045
0003092981
0003092936
0003092948
0003092937
0003092949
0003092970
0003092971
0003092984
0003092973
0003092986
0003093001
0003092953
0003092987
0003093002
0003092954
0003092988
0003093004
0003092978
0003093006
0003092979
0003092959
0003092980
0003092993
0003093009
0003093041
0003093043
0003093024
0003092997
0003093012
0003093044
0003093013
0003093026
0003093000
0003103576
0003103538
0003103615
0003103539
0003103616
0003103595
0003103596
0003103579
0003103598
0003103581
0003103543
0003103620
0003103582
0003103544
0003103621
0003103583
0003103626
0003103603
0003103628
0003103604
0003103666
0003103685
0003103648
0003103631
0003103668
0003103670
0003103689
0003103652
0003103634
0003103671
0003103635
0003103691
0003103637
0003127270
0003127355
0003127338
0003127356
0003127339
0003127318
0003127319
0003127373
0003127321
0003127375
0003127360
0003127343
0003127376
0003127361
0003127344
0003127377
0003127363
0003127326
0003127365
0003127327
0003127349
0003127328
0003127382
0003127368
0003127351
0003127393
0003127332
0003127386
0003127371
0003127394
0003127372
0003127414
0003127434
0003171581
0003171503
0003171601
0003171504
0003171602
0003171622
0003171623
0003171584
0003171625
0003171586
0003171508
0003171606
0003171587
0003171509
0003171607
0003171588
0003171511
0003171630
0003171513
0003171631
0003171612
0003171632
0003171593
0003171516
0003171614
0003171616
0003171636
0003171597
0003171519
0003171617
0003171640
0003171638
0003171642
0003216474
0003216475
0003216476
0003216479
0003216480
0003216481
0003216485
0003216486
0003216493
0003216494
0003216495
0003216496
0003216498
0003216499
0003216500
0003216502
0003216507
0003216513
0003216515
0003216517
0003216520
0003216521
0003216522
0003216527
0003216528
0003216536
0003216537
0003216538
0003216539
0003216540
0003216543
0003216545
0003216551
0003289849
0003289850
0003289851
0003289854
0003289855
0003289856
0003289860
0003289861
0003289868
0003289869
0003289870
0003289871
0003289873
0003289874
0003289875
0003289877
0003289882
0003289888
0003289890
0003289892
0003289895
0003289896
0003289897
0003289902
0003289903
0003289911
0003289912
0003289913
0003289914
0003289915
0003289918
0003289920
0003289926
0001799304
0001799305
0001799306
0001799309
0001799310
0001799311
0001799315
0001799316
0001799322
0001799323
0001799324
0001799325
0001799327
0001799328
0001799329
0001799331
0001799336
0001799342
0001799344
0001799346
0001799349
0001799350
0001799351
0001799356
0001799357
0001799365
0001799366
0001799367
0001799368
0001799369
0001799372
0001799374
0001799380

In [ ]:
df_from2005_to2018

,area,作付面積,10a当たり収量,収穫量,出荷量,対前年産比_作付面積,対前年産比_10ａ当たり収量,対前年産比_収穫量,対前年産比_出荷量,(参考)対平均収量比,term,name,出荷量ランキング,収穫量 - 出荷量
0,北海道,169.0,4910.0,8310.0,7920.0,81.0,99.0,81.0,80.0,97.0,200501-200512,春だいこん,8.0,390.0
1,青森,414.0,5330.0,22100.0,19800.0,88.0,97.0,86.0,86.0,103.0,200501-200512,春だいこん,3.0,2300.0
2,岩手,30.0,2480.0,752.0,374.0,94.0,101.0,96.0,89.0,92.0,200501-200512,春だいこん,40.0,378.0
3,宮城,118.0,3260.0,3840.0,2880.0,100.0,94.0,94.0,93.0,95.0,200501-200512,春だいこん,21.0,960.0
4,秋田,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200501-200512,春だいこん,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28639,（都道府県）_鹿児島県,254.0,1240.0,3150.0,2730.0,90.0,93.0,83.0,83.0,93.0,201801-201812,そらまめ,1.0,420.0
28640,（都道府県）_沖縄県,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201801-201812,そらまめ,NaN,NaN
28641,関東農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201801-201812,そらまめ,NaN,NaN
28642,東海農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201801-201812,そらまめ,NaN,NaN
28643,中国四国農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201801-201812,そらまめ,NaN,NaN

In [ ]:
df_from2005_to2018["name"].unique()

array(['春だいこん', '夏だいこん', '秋冬だいこん', '春夏にんじん', '秋にんじん', '冬にんじん', '春植えばれいしょ',
       '秋植えばれいしょ', '春はくさい', '夏はくさい', '秋冬はくさい', 'こまつな', '春キャベツ', '夏秋キャベツ',
       '冬キャベツ', 'ほうれんそう', 'セルリー', '春レタス', '夏秋レタス', '冬レタス', '春ねぎ', '夏ねぎ',
       '秋冬ねぎ', '冬春きゅうり', '夏秋きゅうり', '冬春トマト', '冬春ミニトマト', '夏秋トマト',
       '夏秋加工用トマト', '夏秋ミニトマト', '冬春ピーマン', '夏秋ピーマン', 'そらまめ'], dtype=object)

# 2019年の出荷ランキングなど

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)
statsDataId_2019 = "0003423835" # 2019年

p["statsDataId"] = statsDataId_2019
print(p["statsDataId"])
url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))
with urllib.request.urlopen(url) as response:
  data = response.read()
d = json.loads(data.decode())

yasai_code_list = ["0110", "0120", "0130", "0160", "0170", "0180", "0220", "0230", "0300", "0310", "0320",
                    "0330", "0350", "0360", "0370", "0390", "0440", "0500", "0520", "0540", "0570", "0580",
                    "0590","0640", "0650", "0730", "0740", "0750", "0760", "0770", "0800", "0820", "0880"]
table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
name_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][1]["CLASS"]
name_info_dic = {dic["@code"] : dic["@name"] for dic in name_info_list}
area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][2]["CLASS"]

df_2019 = pd.DataFrame()
df_list = []

for i, yasai_code in enumerate(yasai_code_list):
  print(yasai_code)
  df_full_ = pd.io.json.json_normalize(table_info_list, sep='_')
  df_ = df_full_[df_full_["@cat02"] == yasai_code]
  df_ = df_.pivot(index="@area", columns="@cat01", values="$").reset_index()

  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "やや不良", "やや良"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)
  
  # @area(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})

  # 統一したカラム名で更新
  df_.columns = ["area", "作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比"]

  # 数値データが str型になっているので、float型に変換
  float_columns = ["作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比",]
  df_[float_columns] = df_[float_columns].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']

  df_["name"] = name_info_dic[yasai_code]

  # トマトからミニトマトと加工用トマト分を引く
  amount_columns = ["作付面積", "収穫量", "出荷量"]
  if re.search('うち', df_["name"][0]) != None:
    if re.search('うち', df_list[i-1]["name"][0]) != None:
      for amount_column in amount_columns:
        df_list[i-2][amount_column] = df_list[i-2][amount_column] - df_[amount_column]
      df_list[i-2]["出荷量ランキング"] = df_list[i-2]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-2]["収穫量 - 出荷量"] = df_list[i-2]["収穫量"] - df_list[i-2]["出荷量"]
    else:
      for amount_column in amount_columns:
        df_list[i-1][amount_column] = df_list[i-1][amount_column] - df_[amount_column]
      df_list[i-1]["出荷量ランキング"] = df_list[i-1]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-1]["収穫量 - 出荷量"] = df_list[i-1]["収穫量"] - df_list[i-1]["出荷量"]
  
  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
  # 収穫量 - 出荷量 を作成
  df_["収穫量 - 出荷量"] = df_["収穫量"] - df_["出荷量"]

  def season_move_2019_str(s_):
    season = re.search(r"[春夏秋冬]植え|[春夏秋冬]{1,2}", s_)
    s = re.sub("_[春夏秋冬]{1,2}", "", s_)
    s = re.sub("トマト_うち", "", s)
    s = re.sub("植え", "", s)
    if season is None:
      return s_
    else:
      return season.group() + s
  df_["name"] = df_["name"].map(season_move_2019_str)

  # df_をリストに追加
  df_list.append(df_)

# df_listからdfを作成
df_2019 = pd.concat(df_list, axis=0, ignore_index=True)

0003423835
0110

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:25: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

0120
0130
0160
0170
0180
0220
0230
0300
0310
0320
0330
0350
0360
0370
0390
0440
0500
0520
0540
0570
0580
0590
0640
0650
0730
0740
0750
0760
0770
0800
0820
0880

In [ ]:
df_2019

,area,作付面積,10a当たり収量,収穫量,出荷量,対前年産比_作付面積,対前年産比_10ａ当たり収量,対前年産比_収穫量,対前年産比_出荷量,(参考)対平均収量比,term,name,出荷量ランキング,収穫量 - 出荷量
0,全国,4350.0,4730.0,205600.0,187000.0,98.0,100.0,98.0,98.0,99.0,201901-201912,春だいこん,0.0,18600.0
1,（全国農業地域）_北海道,195.0,5160.0,10100.0,9570.0,92.0,98.0,91.0,90.0,103.0,201901-201912,春だいこん,6.0,530.0
2,（全国農業地域）_都府県,4150.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,春だいこん,NaN,NaN
3,（全国農業地域）_東北,541.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,春だいこん,NaN,NaN
4,（全国農業地域）_北陸,85.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,春だいこん,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2041,（都道府県）_鹿児島県,257.0,1340.0,3440.0,3010.0,101.0,108.0,109.0,110.0,102.0,201901-201912,そらまめ,1.0,430.0
2042,（都道府県）_沖縄県,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,そらまめ,NaN,NaN
2043,関東農政局,570.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,そらまめ,NaN,NaN
2044,東海農政局,70.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,そらまめ,NaN,NaN
2045,中国四国農政局,396.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,201901-201912,そらまめ,NaN,NaN

In [ ]:
df_2019["name"].unique()

array(['春だいこん', '夏だいこん', '秋冬だいこん', '春夏にんじん', '秋にんじん', '冬にんじん', '春植えばれいしょ',
       '秋植えばれいしょ', '春はくさい', '夏はくさい', '秋冬はくさい', 'こまつな', '春キャベツ', '夏秋キャベツ',
       '冬キャベツ', 'ほうれんそう', 'セルリー', '春レタス', '夏秋レタス', '冬レタス', '春ねぎ', '夏ねぎ',
       '秋冬ねぎ', '冬春きゅうり', '夏秋きゅうり', '冬春トマト', '冬春ミニトマト', '夏秋トマト',
       '夏秋加工用トマト', '夏秋ミニトマト', '冬春ピーマン', '夏秋ピーマン', 'そらまめ'], dtype=object)

# 2020年の出荷ランキングなど

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)

statsDataId_list_2020 = ["0001922164","0001922165","0001922166","0001922169","0001922170","0001922171","0001922175","0001922176","0001922183","0001922184","0001922185", #秋冬はくさい
"0001922186","0001922188","0001922189","0001922190","0001922192","0001922197","0001922203","0001922205","0001922207","0001922210","0001922211","0001922212", #秋冬ねぎ
"0001922217","0001922218","0001922226","0001922227","0001922228","0001922229","0001922230","0001922233","0001922235","0001922241" #2020年
]

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_2020 = pd.DataFrame()
df_list = []

# 各statsDataIdで
for i, statsDataId in enumerate(statsDataId_list_2020):
  # url取得
  p["statsDataId"] = statsDataId
  print(p["statsDataId"])
  url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

  with urllib.request.urlopen(url) as response:
    data = response.read()
  d = json.loads(data.decode())

  # 統計表をデータフレーム化
  table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
  df_ = pd.io.json.json_normalize(table_info_list, sep='_')

  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった
  df_ = df_.pivot(index="@cat01", columns="@cat02", values="$").reset_index()
  
  # 統計表での欠損の意味に近い文字列は欠損値扱い("やや不良", "やや良"は作物の生産量の事だと思うが見たことがない。もしあるなら、ほかの変換方法は考えるべきかと)
  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "やや不良", "やや良"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)
  
  # @area(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][0]["CLASS"]
  df_["@cat01"] = df_["@cat01"].map({dic["@code"] : dic["@name"] for dic in area_info_list})

  # 統一したカラム名で更新
  df_.columns = ["area", "作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比"]

  # 数値データが str型になっているので、float型に変換
  float_columns = ["作付面積", "10a当たり収量", "収穫量", "出荷量", "対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比",]
  df_[float_columns] = df_[float_columns].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']

  # 野菜の名前(name)を追加('TABLE_SUB_CATEGORY3'は「うち、ミニトマト」、CATEGORY2は「冬春トマト」、CATEGORY1は「トマト」のように、カテゴリーの数値が小さいほど野菜としての定義が広くなる)
  try:
    try:
      df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY3']
    except KeyError:
      df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY2']
  except KeyError:
    df_["name"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY1']

  # 途中の年から、CATEGORY2が「冬春」のように省略されるようになったので、CATEGORY1と結合することで統一性を保つ
  # 省略後のCATEGORY2は基本2文字だが、「ばれいしょ」のみ3文字であった(また、３文字は「春ネギ」などがあり文字指定するとそっちも更新されてしまう)ため、
  # 「ばれいしょ」のみ単独で更新、ほかの季節のみnameは2文字指定で更新(２文字以下の野菜はない(ねぎは季節が必ず付くから大丈夫))
  if df_["name"][0]=="春植え" or df_["name"][0]=="秋植え":
    df_["name"] = df_["name"] + "ばれいしょ"
  if len(df_["name"][0]) <= 2:
    df_["name"] = df_["name"] + d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY1']

  # トマトからミニトマトと加工用トマト分を引く
  amount_columns = ["作付面積", "収穫量", "出荷量"]
  if re.match(r'うち、*', df_["name"][0]) != None:
    df_["name"] = df_["name"] + d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['TITLE_SPEC']['TABLE_SUB_CATEGORY2']
    if re.match(r'うち、*', df_list[i-1]["name"][0]) != None:
      for amount_column in amount_columns:
        df_list[i-2][amount_column] = df_list[i-2][amount_column] - df_[amount_column]
      df_list[i-2]["出荷量ランキング"] = df_list[i-2]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-2]["収穫量 - 出荷量"] = df_list[i-2]["収穫量"] - df_list[i-2]["出荷量"]
    else:
      for amount_column in amount_columns:
        df_list[i-1][amount_column] = df_list[i-1][amount_column] - df_[amount_column]
      df_list[i-1]["出荷量ランキング"] = df_list[i-1]["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
      df_list[i-1]["収穫量 - 出荷量"] = df_list[i-1]["収穫量"] - df_list[i-1]["出荷量"]

  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
  # 収穫量 - 出荷量 を作成
  df_["収穫量 - 出荷量"] = df_["収穫量"] - df_["出荷量"]

  # df_をリストに追加
  df_list.append(df_)

  # sleep入れる
  time.sleep(5)

# df_listからdfを作成
df_2020 = pd.concat(df_list, axis=0, ignore_index=True)

0001922164

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:26: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

0001922165
0001922166
0001922169
0001922170
0001922171
0001922175
0001922176
0001922183
0001922184
0001922185
0001922186
0001922188
0001922189
0001922190
0001922192
0001922197
0001922203
0001922205
0001922207
0001922210
0001922211
0001922212
0001922217
0001922218
0001922226
0001922227
0001922228
0001922229
0001922230
0001922233
0001922235
0001922241

# なましいたけ

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)

statsDataId_list_sitake_2020 = ["0003446955"]

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_sitake_2020 = pd.DataFrame()
df_list = []

for i, statsDataId in enumerate(statsDataId_list_sitake_2020):
  # url取得
  p["statsDataId"] = statsDataId
  print(p["statsDataId"])
  url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

  with urllib.request.urlopen(url) as response:
    data = response.read()
  d = json.loads(data.decode())

  # 統計表をデータフレーム化
  table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
  df_ = pd.io.json.json_normalize(table_info_list, sep='_')

  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった
  try:
    try:
      df_ = df_.pivot(index="@area", columns="@cat01", values="$").reset_index()
    except KeyError:
      df_ = df_.pivot(index="@area", columns="@cat02", values="$").reset_index()
  except KeyError:
    df_ = df_.pivot(index="@cat01", columns="@cat02", values="$").reset_index()

  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "-"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)

  # @cat01(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][0]["CLASS"]
  try:
    df_["@cat01"] = df_["@cat01"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  except KeyError:
    df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  
  try:
    col_list = ["@cat01", "001"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  except KeyError:
    col_list = ["@area", "001"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  
  df_["出荷量"] = df_["出荷量"].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']
  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1

  # df_をリストに追加
  df_list.append(df_)

# df_listからdfを作成
df_sitake_2020 = pd.concat(df_list, axis=0, ignore_index=True)

0003446955

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)

statsDataId_list_sitake_2019 = ["0001874285"]

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_sitake_2019 = pd.DataFrame()
df_list = []

for i, statsDataId in enumerate(statsDataId_list_sitake_2019):
  # url取得
  p["statsDataId"] = statsDataId
  print(p["statsDataId"])
  url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

  with urllib.request.urlopen(url) as response:
    data = response.read()
  d = json.loads(data.decode())

  # 統計表をデータフレーム化
  table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
  df_ = pd.io.json.json_normalize(table_info_list, sep='_')

  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった
  try:
    try:
      df_ = df_.pivot(index="@area", columns="@cat01", values="$").reset_index()
    except KeyError:
      df_ = df_.pivot(index="@area", columns="@cat02", values="$").reset_index()
  except KeyError:
    df_ = df_.pivot(index="@cat01", columns="@cat02", values="$").reset_index()

  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "-"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)

  # @cat01(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][0]["CLASS"]
  try:
    df_["@cat01"] = df_["@cat01"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  except KeyError:
    df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  
  try:
    col_list = ["@cat01", "008"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  except KeyError:
    col_list = ["@area", "008"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  
  df_["出荷量"] = df_["出荷量"].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']
  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1

  # df_をリストに追加
  df_list.append(df_)

# df_listからdfを作成
df_sitake_2019 = pd.concat(df_list, axis=0, ignore_index=True)
df_sitake_2019["area"] = df_sitake_2019["area"].map(lambda x: re.sub(r"\d\d", "", x))

0001874285

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)

statsDataId_list_sitake_2018_2017 = ["0001784544", "0003290653"]

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_sitake_2018_2017 = pd.DataFrame()
df_list = []

for i, statsDataId in enumerate(statsDataId_list_sitake_2018_2017):
  # url取得
  p["statsDataId"] = statsDataId
  print(p["statsDataId"])
  url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

  with urllib.request.urlopen(url) as response:
    data = response.read()
  d = json.loads(data.decode())

  # 統計表をデータフレーム化
  table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
  df_ = pd.io.json.json_normalize(table_info_list, sep='_')

  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった
  try:
    try:
      df_ = df_.pivot(index="@area", columns="@cat01", values="$").reset_index()
    except KeyError:
      df_ = df_.pivot(index="@area", columns="@cat02", values="$").reset_index()
  except KeyError:
    df_ = df_.pivot(index="@cat01", columns="@cat02", values="$").reset_index()

  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "-"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)

  # @cat01(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][1]["CLASS"]
  try:
    df_["@cat01"] = df_["@cat01"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  except KeyError:
    df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  
  try:
    col_list = ["@cat01", "001"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  except KeyError:
    col_list = ["@area", "001"]
    df_ = df_[col_list]
    df_.columns = ["area", "出荷量"]
  
  df_["出荷量"] = df_["出荷量"].astype("float64")

  # 期間(term)を追加
  df_["term"] = d['GET_STATS_DATA']['STATISTICAL_DATA']['TABLE_INF']['SURVEY_DATE']
  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1

  # df_をリストに追加
  df_list.append(df_)

# df_listからdfを作成
df_sitake_2018_2017 = pd.concat(df_list, axis=0, ignore_index=True)

0001784544

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:22: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

0003290653

In [ ]:
with open('/content/drive/MyDrive/Competitions/Nishika/yasai/Json/externalData.json') as f:
  p = json.load(f)

# 空のデータフレームと各年・各野菜のデータフレームが入るdf_を格納するリストを作成
df_sitake_2016 = pd.DataFrame()
df_list = []

# url取得
p["statsDataId"] = "0003288425"
print(p["statsDataId"])
url = ('http://api.e-stat.go.jp/rest/3.0/app/json/getStatsData?' + urllib.parse.urlencode(p))

with urllib.request.urlopen(url) as response:
  data = response.read()
d = json.loads(data.decode())

table_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['DATA_INF']['VALUE']
area_info_list = d['GET_STATS_DATA']['STATISTICAL_DATA']['CLASS_INF']["CLASS_OBJ"][3]["CLASS"]

# 統計表をデータフレーム化
df_full = pd.io.json.json_normalize(table_info_list, sep='_')
df_120 = df_full[df_full["@cat02"] == "120"]

time_list = ["2016000000", "2015000000", "2014000000"]

for time in time_list:
  # @area(都道府県)をindexに@cat01/02(出荷量など)をcolumnsにする
  # 途中の年から、columnにあたる列名が @cat01 ⇒ @cat02 になるのでエラー処理をしている。列名が変わるだけで、データ内容の変更は見られなかった
  df_ = df_120[df_120["@time"] == time].pivot(index="@area", columns="@cat01", values="$").reset_index()

  nan_list = ["*", "***", ".", "X", "nc", "…", "‥", "－", "△", "ｘ", "-"]
  for c in nan_list:
    df_.replace(c, np.nan, inplace=True)

  # @cat01(この時点では00001のような数字列になっている)と都道府県名を対応させ更新
  df_["@area"] = df_["@area"].map({dic["@code"] : dic["@name"] for dic in area_info_list})
  
  col_list = ["@area", "100"]
  df_ = df_[col_list]
  df_.columns = ["area", "出荷量"]
  
  df_["出荷量"] = df_["出荷量"].astype("float64")

  # 期間(term)を追加
  df_["term"] = time
  # 出荷ランキング を作成(最も大きい出荷量の行が１位(全国は0位になっている))
  df_["出荷量ランキング"] = df_["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1

  # df_をリストに追加
  df_list.append(df_)

# df_listからdfを作成
df_sitake_2016 = pd.concat(df_list, axis=0, ignore_index=True)

def term_henkan(s_):
  year = re.search(r"\d{4}", s_)
  return year.group() + "01-" + year.group() + "12"

df_sitake_2016["term"] = df_sitake_2016["term"].map(term_henkan)

0003288425

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead

In [ ]:
df_sitake = pd.concat([df_sitake_2020, df_sitake_2019, df_sitake_2018_2017, df_sitake_2016], axis=0, ignore_index=True)
df_sitake["name"] = "なましいたけ"

In [ ]:
df_sitake

     area      出荷量           term  出荷量ランキング    name
0      全国  68923.9  202001-202012       0.0  なましいたけ
1     北海道   5336.8  202001-202012       2.0  なましいたけ
2      青森    199.7  202001-202012      40.0  なましいたけ
3      岩手   4733.3  202001-202012       3.0  なましいたけ
4      宮城    869.0  202001-202012      22.0  なましいたけ
..    ...      ...            ...       ...     ...
331   熊本県   1081.0  201401-201412      19.0  なましいたけ
332   大分県   1170.5  201401-201412      17.0  なましいたけ
333   宮崎県   2090.9  201401-201412       9.0  なましいたけ
334  鹿児島県   1096.5  201401-201412      18.0  なましいたけ
335   沖縄県     32.9  201401-201412      47.0  なましいたけ

[336 rows x 5 columns]

In [ ]:
df_all = pd.concat([df_from2005_to2018, df_2019, df_2020, df_sitake], axis=0, ignore_index=True)
df_all.rename(columns={"name" : "kind_detail"}, inplace=True)
df_all["area"] = df_all["area"].map(lambda x: re.sub(r"^(.*)_|^（.*）_", "", x))
df_all["area"] = df_all["area"].map(lambda x: x if x == "京都" else re.sub(r"[都府県]$", "", x))
df_all["kind_detail"] = df_all["kind_detail"].map(lambda x: re.sub(r"ばれいしょ", "じゃがいも", x))

In [ ]:
sum_list = ["作付面積", "10a当たり収量", "収穫量", "出荷量"]
mean_list =["対前年産比_作付面積", "対前年産比_10ａ当たり収量", "対前年産比_収穫量", "対前年産比_出荷量", "(参考)対平均収量比"]

df_potato = df_all[df_all["kind_detail"] == "春植えじゃがいも"].reset_index()

df_potato_fillna = df_all[df_all["kind_detail"].isin(["春植えじゃがいも" , "秋植えじゃがいも"])]
df_all[df_all["kind_detail"].isin(["春植えじゃがいも" , "秋植えじゃがいも"])] = df_potato_fillna.fillna(0)

df_potato["kind_detail"] = "じゃがいも"
df_potato[sum_list] = df_all[df_all["kind_detail"] == "春植えじゃがいも"].reset_index()[sum_list] + df_all[df_all["kind_detail"] == "秋植えじゃがいも"].reset_index()[sum_list]
df_potato[mean_list] = (df_all[df_all["kind_detail"] == "春植えじゃがいも"].reset_index()[mean_list] + df_all[df_all["kind_detail"] == "秋植えじゃがいも"].reset_index()[mean_list]) / 2
df_potato["出荷量ランキング"] = df_potato["出荷量"].rank(axis=0,ascending=False,method='min',na_option='keep') - 1
df_potato["収穫量 - 出荷量"] = df_potato["収穫量"] - df_potato["出荷量"]

df_potato.drop("index", axis=1, inplace=True)
df_potato.replace(0, np.nan, inplace=True)

df_all = pd.concat([df_all, df_potato], axis=0, ignore_index=True)

In [ ]:
def season_move_str(s_):
    season = re.search(r"[春夏秋冬]{1,2}", s_)
    yasai = re.search(r"ミニトマト|加工用トマト", s_)
    if season is not None and yasai is not None:
      return season.group() + yasai.group()
    else:
      return s_
df_all["kind_detail"] = df_all["kind_detail"].map(season_move_str)

In [ ]:
df_all["kind_detail"].unique()

array(['春だいこん', '夏だいこん', '秋冬だいこん', '春夏にんじん', '秋にんじん', '冬にんじん', '春植えじゃがいも',
       '秋植えじゃがいも', '春はくさい', '夏はくさい', '秋冬はくさい', 'こまつな', '春キャベツ', '夏秋キャベツ',
       '冬キャベツ', 'ほうれんそう', 'セルリー', '春レタス', '夏秋レタス', '冬レタス', '春ねぎ', '夏ねぎ',
       '秋冬ねぎ', '冬春きゅうり', '夏秋きゅうり', '冬春トマト', '冬春ミニトマト', '夏秋トマト',
       '夏秋加工用トマト', '夏秋ミニトマト', '冬春ピーマン', '夏秋ピーマン', 'そらまめ', 'なましいたけ',
       'じゃがいも'], dtype=object)

In [ ]:
df_all.to_csv("/content/drive/MyDrive/Competitions/Nishika/yasai/output/externalData_ranking_v5.csv", index=False)

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Competitions/Nishika/yasai/output/externalData_ranking_v5.csv")

In [ ]:
df

,area,作付面積,10a当たり収量,収穫量,出荷量,対前年産比_作付面積,対前年産比_10ａ当たり収量,対前年産比_収穫量,対前年産比_出荷量,(参考)対平均収量比,term,kind_detail,出荷量ランキング,収穫量 - 出荷量
0,北海道,169.0,4910.0,8310.0,7920.0,81.0,99.0,81.0,80.0,97.0,200501-200512,春だいこん,8.0,390.0
1,青森,414.0,5330.0,22100.0,19800.0,88.0,97.0,86.0,86.0,103.0,200501-200512,春だいこん,3.0,2300.0
2,岩手,30.0,2480.0,752.0,374.0,94.0,101.0,96.0,89.0,92.0,200501-200512,春だいこん,40.0,378.0
3,宮城,118.0,3260.0,3840.0,2880.0,100.0,94.0,94.0,93.0,95.0,200501-200512,春だいこん,21.0,960.0
4,秋田,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200501-200512,春だいこん,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35051,鹿児島,4273.0,3920.0,85420.0,78610.0,92.5,94.0,87.0,86.5,97.5,202001-202012,じゃがいも,114.0,6810.0
35052,沖縄,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202001-202012,じゃがいも,802.0,NaN
35053,関東農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202001-202012,じゃがいも,802.0,NaN
35054,東海農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202001-202012,じゃがいも,802.0,NaN
35055,中国四国農政局,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,202001-202012,じゃがいも,802.0,NaN